import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    vi: {
        // Sidebar & Navigation
        dashboard: "Tổng quan",
        equipment: "Thiết bị",
        transactions: "Nhập / Xuất",
        batches_tab: "Phiếu Nhập Xuất (Tổng)",
        details_tab: "Chi tiết Thiết bị",
        calibrations: "Hiệu chuẩn",
        spare_parts: "Spare Parts",
        internal_export: "Xuất nội bộ",
        admin_group: "Quản trị",
        locations: "Vị trí",
        categories: "Danh mục",
        users: "Tài khoản",
        settings: "Cài đặt",
        order_history: "Lịch sử Order",
        order_progress: "Tiến độ Order",
        manage_equipment: "Quản lý Thiết bị",
        manage_spare_parts: "Quản lý Linh kiện",
        logout: "Đăng xuất",
        account_info: "Thông tin tài khoản",
        change_password: "Đổi mật khẩu",
        current_password: "Mật khẩu hiện tại",
        new_password: "Mật khẩu mới",
        confirm_password: "Xác nhận mật khẩu mới",
        passwords_dont_match: "Mật khẩu xác nhận không khớp",
        change_pass_success: "Đổi mật khẩu thành công!",
        change_pass_error: "Lỗi khi đổi mật khẩu",
        pms_system: "Hệ thống PM System",
        pms_management: "Hệ thống Quản lý Thiết bị",
        factory_management: "Quản lý Nhà máy PM System",

        // Common Actions
        add: "Thêm mới",
        edit: "Sửa",
        delete: "Xóa",
        search: "Tìm kiếm thiết bị...",
        import_csv: "Nhập CSV",
        export_csv: "Xuất CSV",
        save: "Lưu",
        results: "Kết quả",
        cancel: "Hủy",
        confirm: "Xác nhận",
        buttons: "Nút bấm",
        image: "Hình ảnh",
        not_required: "Không yêu cầu",
        clear_filters: "Xóa lọc",

        // Equipment & Inventory
        eq_name: "Tên thiết bị",
        eq_code: "Mã thiết bị",
        status: "Trạng thái",
        location: "Vị trí",
        real_location: "Vị trí Thực tế",
        category: "Phân loại",
        spare_parts: "Spare Parts",
        internal_export: "Xuất nội bộ",
        owner: "Sở hữu",
        at_hse: "Tại kho (At HSE)",
        outside: "Đang ở ngoài (Outside)",
        ok_status: "OK (Tốt)",
        ng_status: "NG (Lỗi)",
        quantity: "Số lượng",
        sender: "Người Giao",
        receiver: "Người Nhận",
        print_handover: "In Biên bản",
        print_gatepass: "Giấy Ra Cổng",
        no_transactions: "Chưa có giao nhận nào",
        scan_import: "QUÉT NHẬP KHO",
        scan_export: "QUÉT XUẤT KHO",
        confirm_add: "Xác nhận Thêm",
        role: "Vai trò",
        admin_role: "Quản trị viên",
        user_role: "Người dùng",
        manager_role: "Quản lý",
        update_role_success: "Cập nhật vai trò thành công!",
        delete_user_confirm: "Bạn có chắc chắn muốn xóa tài khoản này?",
        delete_user_success: "Xóa tài khoản thành công!",
        calibrations_title: "Quản lý Hiệu chuẩn",
        calibration_desc: "Quản lý và cập nhật lịch sử bảo trì, hiệu chuẩn thiết bị",
        all: "Tất cả thiết bị",
        upcoming: "Sắp đến hạn",
        overdue: "Quá hạn hiệu chuẩn",
        approve: "Duyệt",
        approved: "Đã duyệt",
        pending: "Chờ duyệt",
        calibration_all: "Tất cả thiết bị",
        calibration_upcoming: "Sắp đến hạn",
        calibration_overdue: "Quá hạn hiệu chuẩn",
        days_to_calibrate: "Số ngày dự báo",
        within_days: "Trong vòng {days} ngày",
        history_view: "Xem lịch sử",
        update_result: "Cập nhật kết quả",
        calibration_result: "Kết quả hiệu chuẩn",
        technician: "Kỹ thuật viên",
        certificate_number: "Số chứng chỉ / GCN",
        passed: "Đạt (Passed)",
        failed: "Không đạt (Failed)",
        needs_repair: "Cần sửa chữa",
        save_calibration_success: "Đã lưu lịch sử hiệu chuẩn thành công",
        search_placeholder: "Tìm theo Mã, Tên hoặc S/N...",
        bulk_update: "Cập nhật hàng loạt",
        select_all: "Chọn tất cả",
        selected_items_count: "Đã chọn {count} thiết bị",
        filter_line: "Lọc theo Chuyền",
        filter_station: "Lọc theo Công đoạn",
        all_lines: "Tất cả Chuyền",
        all_stations: "Tất cả Công đoạn",
        status_old: "Trạng thái cũ",
        items_count: "thiết bị",
        total: "Tổng số",
        schedule: "Lịch trình",
        calibration_log: "Nhật ký hiệu chuẩn",
        select_date: "Chọn ngày",
        total_calibrated_today: "Tổng thiết bị đã hiệu chuẩn hôm nay",
        searching_in_category: "trong danh mục",

        // Transactions
        import: "Nhập kho",
        export: "Xuất kho",
        scrap: "Xuất phế liệu",
        create_import: "Lập Phiếu NHẬP Kho",
        create_export: "Lập Phiếu XUẤT Kho",
        create_scrap: "Lập Phiếu XUẤT PHẾ",
        scrap_weight: "Khối lượng phế",
        scrap_unit: "Đơn vị phế",
        batch_code: "Mã phiếu",
        transaction_date: "Ngày giờ",
        person_in_charge: "Người Phụ Trách",
        related_person: "Người Giao/Nhận",
        purpose: "Mục đích",
        evidence: "Minh chứng",
        scan_placeholder: "Nhấn đây và QUÉT...",
        scan_instruction: "Sử dụng Máy Quét Mã Vạch (Gõ bằng súng scan hoặc nhập tay và nhấn Enter)",
        save_batch: "Lưu Phiếu",
        handover_info: "Thông Tin Người Giao (Bên Xuất)",
        receive_info: "Thông Tin Người Nhận (Bên Nhập)",
        from_contacts: "Chọn từ danh bạ",
        empty_contacts: "Danh bạ rỗng",
        you: "Bạn",
        save_contact_auto: "Tự động lưu thông tin ĐỐI TÁC vào Danh bạ",
        purpose_label: "Mục đích Xuất/Nhập",
        notes_label: "Ghi chú chung",
        items_rows: "Dòng mặt hàng",
        action_label: "Hành động",
        import_to_stock: "NHẬP VÀO KHO",
        export_from_stock: "XUẤT KHỎI KHO",
        stock: "Tồn kho",
        available: "Sẵn sàng",
        in_use: "Đang dùng",
        maintenance: "Bảo trì",
        code: "Mã",
        items_list: "Danh sách Giao dịch",
        batches_list: "Danh sách Phiếu hệ thống",
        clear_filter: "Bỏ lọc",
        search_results: "Kết quả tìm kiếm",
        total_equipment: "Tổng thiết bị",
        calibration_expired: "Hết hạn hiệu chuẩn",
        recently_updated: "Thiết bị mới cập nhật",
        expired_badge: "Hết hạn!",
        valid_badge: "Còn hạn",
        no_data: "Chưa có dữ liệu.",
        line_station: "Chuyền / Công đoạn",
        calibration_status: "Tình trạng Hiệu chuẩn",
        calibration_schedule: "Lịch trình hiệu chuẩn",
        last_calibration: "Ngày hiệu chuẩn cuối",
        next_calibration: "Ngày đến hạn tiếp theo",
        no_calibrations: "Không có thiết bị nào cần hiệu chuẩn",
        none: "Chưa có",

        // Login & Register
        login: "Đăng nhập",
        register: "Đăng ký",
        username: "Tên đăng nhập",
        password: "Mật khẩu",
        full_name: "Họ và tên",
        role: "Vai trò",
        dont_have_account: "Chưa có tài khoản?",
        have_account: "Đã có tài khoản?",
        authenticating: "Đang xác thực...",
        login_failed: "Đăng nhập thất bại",
        network_error: "Không thể kết nối tới Server (Network Error)",
        register_now: "Đăng ký ngay",
        placeholder_username: "Nhập username",
        placeholder_password: "Mật khẩu",
        required: "Bắt buộc",
        unit: "Đơn vị",
        position: "Chức vụ",
        department: "Bộ phận",
        company: "Công ty",
        employee_id: "Mã nhân viên",
        register_title: "Đăng ký tài khoản",
        pms_join_desc: "Tham gia hệ thống quản lý PMS",
        processing: "Đang xử lý...",
        submit_registration: "Gửi yêu cầu đăng ký",
        register_success: "Đăng ký thành công! Đang chuyển hướng...",
        register_failed: "Đăng ký thất bại",
        loading: "Đang tải...",
        settings_page: "Cài đặt hệ thống",
        general_system: "Hệ thống chung",
        no_equipment_found: "Chưa có thiết bị nào trong danh sách.",
        eq_code_placeholder: "(Tự động sinh nếu để trống)",
        eq_name_placeholder: "VD: Jig Kiểm Tra, Súng Bắn Vít...",
        part_no: "Mã Part No (Model thiết bị)",
        serial_no: "Số Serial",
        category_label: "Phân loại Thiết bị",
        model_label: "Model / Kiểu dáng",
        owner_label: "Đơn vị sở hữu",
        jig_id: "Dùng cho Jig ID",
        initial_quantity: "Số lượng Ban đầu",
        installation_location: "Vị trí lắp đặt (Line / Station)",
        select_line: "Chọn line...",
        select_station: "Trạm / Máy...",
        select_jig: "Jig / Tổ...",
        location_note: "Lưu ý: Nếu không chọn Station/Jig, thiết bị sẽ ở 'Hệ thống chung'.",
        current_status: "Trạng thái hiện tại",
        illustration_image: "Ảnh minh họa",
        equipment_identity: "Thiết bị (Mã/Tên)",
        calibration_date: "Ngày hiệu chuẩn",
        expiry_date_label: "Ngày hết hạn hiệu chuẩn",
        scan_at_least_one: "Vui lòng quét ít nhất một thiết bị!",
        fill_person_info: "Vui lòng điền đầy đủ thông tin người giao/nhận!",
        add_equipment_error: "Lỗi khi thêm thiết bị",
        image_upload_error: "Lỗi tải ảnh. Vui lòng kiểm tra Server.",
        no_data_export: "Không có dữ liệu để xuất!",
        csv_empty_error: "File CSV bị trống hoặc sai định dạng!",
        confirm_import: "Xác nhận Import tự động {count} thiết bị vào hệ thống CSDL?",
        import_complete: "Đã hoàn tất Import Bulk Data! \n- Thành công: {success} \n- Lỗi/Trùng lặp: {fail}",
        csv_read_error: "Lỗi đọc file CSV: ",
        csv_header_error: "File CSV không hợp lệ hoặc sai định dạng tiêu đề! Cần có: {headers}",
        confirm_add_success: "Thêm mới thành công! Bạn có muốn IN TEM NHÃN cho thiết bị này ngay không?",
        equipment_not_found: "Không tìm thấy mã: {code}\nBạn có muốn sang trang Quản lý Thiết Bị để Tạo mới?",
        duplicate_item: "Thiết bị/Vật tư này đã có trong danh sách phiếu hiện tại!",
        export_error_outside: "Dừng lại! Không thể Xuất kho thiết bị [{name}] vì hiện tại máy đang ở TRẠNG THÁI NGOÀI.",
        import_error_at_hse: "Dừng lại! Không thể Nhập kho thiết bị [{name}] vì hiện tại máy đang ở TRẠNG THÁI TẠI KHO (HSE).",
        stock_empty_error: "Kho đã hết sạch vật tư [{name}] (Tồn: 0). Vui lòng nhập thêm mới có thể xuất!",
        no_internal_code_print: "Không tìm thấy mã nội bộ để in tem!",
        reprint_label: "In Lại Tem Nhãn",
        reprint_label_thermal: "🖨️ IN LẠI NGAY (Máy in tem nhiệt)",
        upload_evidence_success: "Upload minh chứng thành công!",
        upload_evidence_error: "Lỗi khi upload: ",
        save_transaction_success: "Lưu giao dịch & Cập nhật danh bạ THÀNH CÔNG!",
        save_transaction_error: "Thao tác thất bại. Vui lòng kiểm tra lại kết nối!",
        close: "Đóng",
        print_label_thermal: "🖨️ IN TEM NHÃN (Máy in nhiệt)",
        add_new_category: "Thêm loại mới",
        category_name: "Tên loại",
        category_list: "Danh sách loại",
        remember_username: "Ghi nhớ tên đăng nhập",
    },
    en: {
        // Sidebar & Navigation
        dashboard: "Dashboard",
        equipment: "Equipment",
        transactions: "Transactions",
        batches_tab: "Batches (Summary)",
        details_tab: "Items (Detail)",
        calibrations: "Calibration",
        spare_parts: "Spare Parts",
        internal_export: "Internal Export",
        admin_group: "Administration",
        locations: "Locations",
        categories: "Categories",
        users: "Users",
        settings: "Settings",
        order_history: "Order History",
        order_progress: "Order Progress",
        manage_equipment: "Manage Equipment",
        manage_spare_parts: "Manage Spare Parts",
        logout: "Logout",
        account_info: "Account Info",
        change_password: "Change Password",
        current_password: "Current Password",
        new_password: "New Password",
        confirm_password: "Confirm New Password",
        passwords_dont_match: "Passwords do not match",
        change_pass_success: "Password changed successfully!",
        change_pass_error: "Error changing password",
        pms_system: "PM System",
        pms_management: "Equipment Management System",
        factory_management: "PM Factory Management",

        // Common Actions
        add: "Add New",
        edit: "Edit",
        delete: "Delete",
        search: "Search equipment...",
        import_csv: "Import CSV",
        export_csv: "Export CSV",
        results: "Results",
        cancel: "Cancel",
        confirm: "Confirm",
        buttons: "Buttons",
        image: "Image",
        not_required: "Not required",
        clear_filters: "Clear Filters",

        // Equipment & Inventory
        eq_name: "Equipment Name",
        eq_code: "Equipment Code",
        status: "Status",
        location: "Location",
        real_location: "Actual Location",
        category: "Category",
        spare_parts: "Spare Parts",
        internal_export: "Internal Export",
        owner: "Owner",
        at_hse: "At HSE",
        outside: "Outside",
        ok_status: "OK (Good)",
        ng_status: "NG (Error)",
        quantity: "Quantity",
        sender: "Sender",
        receiver: "Receiver",
        print_handover: "Handover Note",
        print_gatepass: "Gate Pass",
        no_transactions: "No transactions found",
        scan_export: "Scan for EXPORT",
        confirm_add: "Confirm Add",
        role: "Role",
        admin_role: "Administrator",
        user_role: "User",
        manager_role: "Manager",
        update_role_success: "Role updated successfully!",
        delete_user_confirm: "Are you sure you want to delete this account?",
        delete_user_success: "User deleted successfully!",
        calibrations_title: "Calibration Management",
        calibration_desc: "Manage and update equipment maintenance and calibration history",
        all: "All Equipment",
        upcoming: "Upcoming",
        overdue: "Overdue",
        approve: "Approve",
        approved: "Approved",
        pending: "Pending",
        calibration_all: "All Equipment",
        calibration_upcoming: "Upcoming",
        calibration_overdue: "Overdue",
        days_to_calibrate: "Days Forecast",
        within_days: "Within {days} days",
        history_view: "View History",
        update_result: "Update Result",
        calibration_result: "Calibration Result",
        technician: "Technician",
        certificate_number: "Cert Number",
        passed: "Passed",
        failed: "Failed",
        needs_repair: "Needs Repair",
        save_calibration_success: "Calibration history saved successfully",
        search_placeholder: "Search by Code, Name or S/N...",
        bulk_update: "Bulk Update",
        select_all: "Select All",
        selected_items_count: "{count} items selected",
        filter_line: "Filter by Line",
        filter_station: "Filter by Station",
        all_lines: "All Lines",
        all_stations: "All Stations",
        status_old: "Old Status",
        items_count: "items",
        total: "Total",
        schedule: "Schedule",
        calibration_log: "Calibration Log",
        select_date: "Select Date",
        total_calibrated_today: "Total calibrated today",
        searching_in_category: "in category",

        // Transactions
        import: "Import",
        export: "Export",
        scrap: "Scrap Export",
        create_import: "Create IMPORT Note",
        create_export: "Create EXPORT Note",
        create_scrap: "Create SCRAP Note",
        scrap_weight: "Scrap weight",
        scrap_unit: "Scrap unit",
        batch_code: "Batch Code",
        transaction_date: "Date & Time",
        person_in_charge: "Person in Charge",
        related_person: "Related Person",
        purpose: "Purpose",
        evidence: "Evidence",
        scan_placeholder: "Click here to SCAN...",
        scan_instruction: "Use Barcode Scanner (Scan gun or type and press Enter)",
        save_batch: "Save Note",
        handover_info: "Sender Information (Export)",
        receive_info: "Receiver Information (Import)",
        from_contacts: "Select from contacts",
        empty_contacts: "No contacts",
        you: "You",
        save_contact_auto: "Auto-save partner to contacts",
        purpose_label: "Purpose",
        notes_label: "General Notes",
        items_rows: "Item Rows",
        action_label: "Action",
        import_to_stock: "IMPORT TO STOCK",
        export_from_stock: "EXPORT FROM STOCK",
        stock: "Stock",
        available: "Available",
        in_use: "In Use",
        maintenance: "Maintenance",
        code: "Code",
        items_list: "Transaction Items List",
        batches_list: "System Batches List",
        clear_filter: "Clear Filter",
        search_results: "Search Results",
        total_equipment: "Total Equipment",
        calibration_expired: "Expired Calibration",
        recently_updated: "Recently Updated Items",
        expired_badge: "Expired!",
        valid_badge: "Valid",
        no_data: "No data available.",
        line_station: "Line / Station",
        calibration_status: "Calibration Status",
        calibration_schedule: "Calibration Schedule",
        last_calibration: "Last Calibration",
        next_calibration: "Next Deadline",
        no_calibrations: "No equipment needs calibration",
        none: "None",

        // Login & Register
        login: "Login",
        register: "Register",
        username: "Username",
        password: "Password",
        full_name: "Full Name",
        role: "Role",
        dont_have_account: "Don't have an account?",
        have_account: "Already have an account?",
        authenticating: "Authenticating...",
        login_failed: "Login failed",
        network_error: "Cannot connect to server (Network Error)",
        register_now: "Register now",
        placeholder_username: "Enter username",
        placeholder_password: "Password",
        required: "Required",
        unit: "Unit",
        position: "Position",
        department: "Department",
        company: "Company",
        employee_id: "Employee ID",
        register_title: "Create Account",
        pms_join_desc: "Join the PMS Management System",
        processing: "Processing...",
        submit_registration: "Submit Registration",
        register_success: "Registration successful! Redirecting...",
        register_failed: "Registration failed",
        loading: "Loading...",
        settings_page: "System Settings",
        general_system: "General System",
        no_equipment_found: "No equipment found in list.",
        eq_code_placeholder: "(Auto-generated if empty)",
        eq_name_placeholder: "e.g. Test Jig, Screw Driver...",
        part_no: "Part No",
        serial_no: "Serial No",
        category_label: "Equipment Category",
        model_label: "Model / Design",
        owner_label: "Owner Company",
        jig_id: "For Jig ID",
        initial_quantity: "Initial Quantity",
        installation_location: "Installation Position (Line / Station)",
        select_line: "Select line...",
        select_station: "Station / Machine...",
        select_jig: "Jig / Group...",
        location_note: "Note: If Station/Jig ignored, item stays in 'General System'.",
        current_status: "Current Status",
        illustration_image: "Illustration Image",
        equipment_identity: "Equipment (Code/Name)",
        calibration_date: "Calibration Date",
        expiry_date_label: "Calibration Expiry Date",
        bulk_items_desc: "Bulk Items (Quantity based)",
        scan_at_least_one: "Please scan at least one item!",
        fill_person_info: "Please fill in all person info!",
        add_equipment_error: "Error adding equipment",
        image_upload_error: "Image upload failed. Check Server.",
        no_data_export: "No data to export!",
        csv_empty_error: "CSV file is empty or invalid!",
        confirm_import: "Confirm automatic import of {count} items into database?",
        import_complete: "Bulk Import Complete! \n- Success: {success} \n- Error/Duplicate: {fail}",
        csv_read_error: "CSV read error: ",
        csv_header_error: "Invalid CSV file or wrong headers! Required: {headers}",
        confirm_add_success: "Added successfully! Do you want to PRINT LABEL for this equipment now?",
        equipment_not_found: "Code not found: {code}\nDo you want to go to Equipment Management to create a new one?",
        duplicate_item: "This equipment/item is already in the current batch!",
        export_error_outside: "Stop! Cannot EXPORT [{name}] because it is currently OUTSIDE.",
        import_error_at_hse: "Stop! Cannot IMPORT [{name}] because it is currently AT HSE.",
        stock_empty_error: "Stock is empty for [{name}] (Stock: 0). Please import before export!",
        no_internal_code_print: "No internal code found for printing label!",
        reprint_label: "Reprint Label",
        reprint_label_thermal: "🖨️ REPRINT NOW (Thermal printer)",
        upload_evidence_success: "Evidence uploaded successfully!",
        upload_evidence_error: "Upload error: ",
        save_transaction_success: "Transaction saved & Contacts updated SUCCESSFULLY!",
        save_transaction_error: "Operation failed. Please check your connection!",
        close: "Close",
        print_label_thermal: "🖨️ PRINT LABEL (Thermal Printer)",
        add_new_category: "Add New Category",
        category_name: "Category Name",
        category_list: "Category List",
        remember_username: "Remember username",
    },
    ko: {
        // Sidebar & Navigation
        dashboard: "대시보드",
        equipment: "설비 관리",
        transactions: "입고 / 출고",
        batches_tab: "전표 요약 (일괄)",
        details_tab: "상세 내역 (개별)",
        calibrations: "교정 관리",
        spare_parts: "스페어 파트",
        admin_group: "시스템 관리",
        locations: "위치",
        categories: "카테고리",
        users: "사용자",
        settings: "설정",
        order_history: "주문 내역",
        order_progress: "주문 진행",
        manage_equipment: "장비 관리",
        manage_spare_parts: "부품 관리",
        logout: "로그아웃",
        pms_system: "PM 시스템",
        pms_management: "설비 관리 시스템",
        factory_management: "PM 공장 관리 시스템",

        // Common Actions
        add: "신규 추가",
        edit: "수정",
        delete: "삭제",
        search: "장비 검색...",
        import_csv: "CSV 가져오기",
        export_csv: "CSV 내보내기",
        results: "결과",
        cancel: "취소",
        confirm: "확인",
        buttons: "버튼",
        image: "이미지",
        not_required: "필요 없음",
        clear_filters: "필터 초기화",

        // Equipment & Inventory
        eq_name: "설비명",
        eq_code: "설비 코드",
        status: "상태",
        location: "위치",
        real_location: "실제 위치",
        category: "분류",
        owner: "소유자",
        at_hse: "HSE 내",
        outside: "외부(출고)",
        ok_status: "OK (정상)",
        ng_status: "NG (불량)",
        quantity: "수량",
        sender: "인계자 (보내는 이)",
        receiver: "인수자 (받는 이)",
        print_handover: "인수인계서 출력",
        print_gatepass: "반출증 출력",
        no_transactions: "거래 내역이 없습니다",
        scan_import: "입고 장비 스캔",
        scan_export: "출고 장비 스캔",
        confirm_add: "추가 확인",
        role: "권한",
        admin_role: "관리자",
        user_role: "사용자",
        manager_role: "매니저",
        update_role_success: "권한이 성공적으로 업데이트되었습니다!",
        delete_user_confirm: "이 계정을 삭제하시겠습니까?",
        delete_user_success: "계정이 성공적으로 삭제되었습니다!",
        calibrations_title: "교정 관리",
        calibration_desc: "장비 유지 관리 및 교정 이력 관리 및 업데이트",
        all: "모든 장비",
        upcoming: "공정 예정",
        overdue: "교정 만료",
        approve: "승인",
        approved: "승인됨",
        pending: "대기 중",
        calibration_all: "모든 장비",
        calibration_upcoming: "공정 예정",
        calibration_overdue: "교정 만료",
        days_to_calibrate: "예측 일수",
        within_days: "{days}일 이내",
        history_view: "이력 보기",
        update_result: "결과 업데이트",
        calibration_result: "교정 결과",
        technician: "기술자",
        certificate_number: "인증서 번호",
        passed: "합격",
        failed: "불합격",
        needs_repair: "수리 필요",
        save_calibration_success: "교정 이력이 성공적으로 저장되었습니다",
        search_placeholder: "코드, 이름 또는 S/N으로 검색...",
        bulk_update: "일괄 업데이트",
        select_all: "전체 선택",
        selected_items_count: "{count}개 선택됨",
        filter_line: "라인별 필터",
        filter_station: "공정별 필터",
        all_lines: "전체 라인",
        all_stations: "전체 공정",
        status_old: "이전 상태",
        items_count: "개",
        total: "합계",
        schedule: "교정 일정",
        calibration_log: "교정 로그",
        select_date: "날짜 선택",
        total_calibrated_today: "오늘 교정된 총 설비",
        searching_in_category: "카테고리 내",
        results: "검색 결과",

        // Transactions
        import: "입고",
        export: "출고",
        create_import: "입고 전표 생성",
        create_export: "출고 전표 생성",
        batch_code: "전표 번호",
        transaction_date: "일시",
        person_in_charge: "담당자",
        related_person: "인계/인수자",
        purpose: "목적",
        evidence: "증빙 자료",
        scan_placeholder: "여기를 클릭하여 스캔하세요...",
        scan_instruction: "바코드 스캐너 사용 (스캔 건 사용 또는 직접 입력 후 Enter)",
        save_batch: "전표 저장",
        handover_info: "인계자 정보 (출고측)",
        receive_info: "인수자 정보 (입고측)",
        from_contacts: "연락처에서 선택",
        empty_contacts: "연락처 없음",
        you: "본인",
        save_contact_auto: "거래처 정보를 연락처에 자동 저장",
        purpose_label: "목적",
        notes_label: "일반 메모",
        items_rows: "품목 수",
        action_label: "작업 내용",
        import_to_stock: "재고 입고 처리",
        export_from_stock: "재고 출고 처리",
        stock: "재고",
        available: "사용 가능",
        in_use: "사용 중",
        maintenance: "유지 보수",
        code: "코드",
        items_list: "장비 거래 내역",
        batches_list: "시스템 전표 목록",
        clear_filter: "필터 해제",
        search_results: "검색 결과",
        total_equipment: "총 설비 수",
        calibration_expired: "교정 기한 만료",
        recently_updated: "최근 업데이트 설비",
        expired_badge: "기한 만료!",
        valid_badge: "기한 내",
        no_data: "데이터가 없습니다.",
        line_station: "라인 / 공정",
        calibration_status: "교정 상태",
        calibration_schedule: "교정 일정 관리",
        last_calibration: "마지막 교정일",
        next_calibration: "차기 교정 기한",
        no_calibrations: "교정 대상 설비가 없습니다",
        update_result: "결과 업데이트",
        none: "내역 없음",

        // Login & Register
        login: "로그인",
        register: "회원가입",
        username: "사용자 ID",
        password: "비밀번호",
        full_name: "성명",
        role: "권한",
        dont_have_account: "계정이 없으신가요?",
        have_account: "이미 계정이 있으신가요?",
        authenticating: "계정 확인 중...",
        login_failed: "로그인 실패",
        network_error: "서버에 연결할 수 없습니다 (네트워크 오류)",
        register_now: "지금 가입하기",
        placeholder_username: "사용자 ID 입력",
        placeholder_password: "비밀번호",
        required: "필수",
        unit: "단위",
        position: "직위",
        department: "부서",
        company: "회사명",
        employee_id: "사번 (사원번호)",
        register_title: "계정 생성",
        pms_join_desc: "PMS 관리 시스템에 가입하세요",
        processing: "처리 중...",
        submit_registration: "등록 요청 제출",
        register_success: "등록 성공! 로그인 페이지로 이동합니다...",
        register_failed: "등록 실패",
        loading: "로딩 중...",
        settings_page: "시스템 설정",
        general_system: "공통 시스템",
        no_equipment_found: "목록에 설비가 없습니다.",
        eq_code_placeholder: "(비워두면 자동 생성)",
        eq_name_placeholder: "예: 테스트 지그, 전동 드라이버...",
        part_no: "파트 번호",
        serial_no: "시리얼 번호",
        category_label: "설비 분류",
        model_label: "모델 / 형식",
        owner_label: "소유 업체",
        jig_id: "지그 ID용",
        initial_quantity: "초기 수량",
        installation_location: "설치 위치 (라인 / 스테이션)",
        select_line: "라인 선택...",
        select_station: "스테이션 / 설비...",
        select_jig: "지그 / 조...",
        location_note: "참고: 스테이션/지그 미선택 시 해당 라인의 '공통 시스템'으로 저장됩니다.",
        current_status: "현재 상태",
        illustration_image: "참고 이미지",
        calibration_desc: "장비 유지 관리 및 교정 이력 관리 및 업데이트",
        equipment_identity: "장비 (코드/이름)",
        calibration_date: "교정 날짜",
        expiry_date_label: "교정 유효 기간",
        bulk_items_desc: "대량 자재 (수량 기반)",
        scan_at_least_one: "최소 한 개의 항목을 스캔하십시오!",
        fill_person_info: "담당자 정보를 모두 입력하십시오!",
        add_equipment_error: "설비 추가 중 오류 발생",
        image_upload_error: "이미지 업로드 실패. 서버를 확인하십시오.",
        no_data_export: "내보낼 데이터가 없습니다!",
        csv_empty_error: "CSV 파일이 비어 있거나 형식이 잘못되었습니다!",
        confirm_import: "{count}개의 항목을 데이터베이스로 자동 가져오시겠습니까?",
        import_complete: "대량 가져오기 완료! \n- 성공: {success} \n- 오류/중복: {fail}",
        csv_read_error: "CSV 읽기 오류: ",
        csv_header_error: "잘못된 CSV 파일 또는 헤더가 잘못되었습니다! 필수: {headers}",
        confirm_add_success: "성공적으로 추가되었습니다! 지금 이 설비의 라벨을 출력하시겠습니까?",
        equipment_not_found: "코드를 찾을 수 없습니다: {code}\n새 설비를 생성하기 위해 설비 관리 페이지로 이동하시겠습니까?",
        duplicate_item: "이 설비/품목은 이미 현재 전표에 포함되어 있습니다!",
        export_error_outside: "중지! [{name}]은(는) 현재 외부 상태이므로 출고할 수 없습니다.",
        import_error_at_hse: "중지! [{name}]은(는) 현재 HSE 창고 상태이므로 입고할 수 없습니다.",
        stock_empty_error: "[{name}]의 재고가 없습니다 (재고: 0). 출고 전 입고가 필요합니다!",
        no_internal_code_print: "라벨 인쇄를 위한 내부 코드를 찾을 수 없습니다!",
        reprint_label: "라벨 재인쇄",
        reprint_label_thermal: "🖨️ 즉시 재인쇄 (열전사 프린터)",
        upload_evidence_success: "증빙 업로드 성공!",
        upload_evidence_error: "업로드 오류: ",
        save_transaction_success: "거래 저장 및 연락처 업데이트가 완료되었습니다!",
        save_transaction_error: "작업에 실패했습니다. 연결을 확인하십시오!",
        close: "닫기",
        print_label_thermal: "🖨️ 라벨 인쇄 (열전사 프린터)",
        add_new_category: "새 분류 추가",
        category_name: "분류 이름",
        category_list: "분류 목록",
        remember_username: "사용자 이름 기억",
    }
};

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState(localStorage.getItem('pms_lang') || 'vi');

    useEffect(() => {
        localStorage.setItem('pms_lang', lang);
    }, [lang]);

    const t = (key) => {
        return translations[lang][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
